### ISSUE TITLE
Remove file watch handler after executing

### ISSUE THREAD

**Issue by ottiker** [IonicaBizau/node-filewatcher#1]
In some cases it would be handy to append a `FileWatcher` callback handler, that is executed only once.
Example:

``` js
// Dependencies
var FileWatcher = require("fwatcher");

// Listen once for a change
FileWatcher.once(__dirname + "/test.txt", function (err, ev, path) {
    /* executed only once */
});
```

Or is this already possible?

**Comment by IonicaBizau** [comment]
Currently this is not possible. Thanks for idea! :+1:

**Comment by IonicaBizau** [comment]
BTW, what's the use-case?

**Comment by ottiker** [comment]
A use case could be a file cache, that removes a file when it changes.
1. A file is loaded into the cache and a `fwatcher` handler is appended, to listen to changes on that file.
2. File get's changed `fwatcher` handler removes the file from the cache.
3. File is requested again and now another `fwatcher` handler is appended.

If there would be an option like `once`, such a problem could be solved without writing your own checks, to make sure a `fwatcher` handler is not appended multiple times.
